# Generated by Django 2.2.4 on 2019-08-18 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userbook_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookvote',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.UserBook'),
        ),
    ]
