# Generated by Django 2.2.4 on 2019-08-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190818_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userbookvote',
            name='ip_address',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
