# Generated by Django 2.2.4 on 2019-08-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190821_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='description',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
